name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Get Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: onichandame/epics-proxy
          username: ${{ secrets.DOCKER_USERNAME }}
          password : ${{ secrets.DOCKER_PASSWORD }}
